jquery_lang_js.prototype.lang.fr = {
	'Choose the options below then submit, and you will get your own unique password instantly generated by our script. All random passwords generated by this software are available on your local computer only. No passwords are transferred over the Internet. No personal data is stored by or captured through the site.': 'Choisissez les options ci-dessous puis validez, vous obtiendrez un mot de passe g&eacute;n&eacute;r&eacute; instantan&eacute;ment par notre logiciel. Tous les mots de passe g&eacute;n&eacute;r&eacute; par cette application sont al&eacute;atoires et disponibles uniquement sur votre ordinateur. Aucun mot de passe n\'est transf&eacute;r&eacute; &agrave; travers Internet. Aucune information personnelle n\'est collect&eacute;e ou stock&eacute;e sur ce site.',
	'You will always find the latest source code version of this script in our GitHub repository. You can check out the source code :': 'La version la plus r&eacute;cente de cette application est disponible dans notre d&eacute;p&ocirc;t GitHub. Vous pouvez obtenir le code source &agrave; cette adresse :',
	'Powered by Clicface': 'R&eacute;alis&eacute; par Clicface',
	'password character length': 'nombre de caract&egrave;res dans le mot de passe',
	'string letters': 'lettres minuscules',
	'capital letters': 'lettres majuscules',
	'digits': 'chiffres',
	'special symbols': 'caract&egrave;res sp&eacute;ciaux',
	'ambiguous characters': 'caract&egrave;res ambigus',
	'Generate Password': 'G&eacute;n&eacute;rer le mot de passe',
	'Please make at least one selection': 'veuillez effectuer au moins un choix',
}