jquery_lang_js.prototype.lang.fr = {
	'Choose the options below then submit, and you will get your own unique password instantly generated by our script.': 'Choisissez les options ci-dessous puis validez, vous obtiendrez un mot de passe g&eacute;n&eacute;r&eacute; instantan&eacute;ment par notre logiciel.',
	'All random passwords generated by this software are available on your local computer only. No passwords are transferred over the Internet.': 'Tous les mots de passe g&eacute;n&eacute;r&eacute; par cette application sont al&eacute;atoires et disponibles uniquement sur votre ordinateur. Aucun mot de passe n\'est transf&eacute;r&eacute; &agrave; travers Internet.',
	'Powered by Clicface': 'R&eacute;alis&eacute; par Clicface',
	'password character length': 'nombre de caract&egrave;res dans le mot de passe',
	'string letters': 'lettres minuscules',
	'capital letters': 'lettres majuscules',
	'digits': 'chiffres',
	'hyphen, underscore': 'tiret, underscore',
	'special symbols': 'caract&egrave;res sp&eacute;ciaux',
	'ambiguous characters': 'caract&egrave;res ambigus',
	'Generate Password': 'G&eacute;n&eacute;rer le mot de passe',
	'Please make at least one selection': 'veuillez effectuer au moins un choix',
}